packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - argon2
  - esbuild
  - unrs-resolver
allowBuilds:
  argon2: true
  electron: true
  electron-winstaller: true
  esbuild: true
  unrs-resolver: true
