/*
 * Generated by scripts/theme-tokens.ts — do not hand-edit.
 * The canonical values live in packages/ui/src/tokens.css.
 */

export const designTokens = {
  primary: '#4f5f90',
  onPrimary: '#ffffff',
  primaryContainer: '#dce2ff',
  onPrimaryContainer: '#081943',
  secondaryContainer: '#dee2f3',
  tertiaryContainer: '#ffd7f5',
  surface: '#fbf8ff',
  surfaceContainer: '#efedf4',
  surfaceContainerLowest: '#ffffff',
  canvas: '#f5f2f9',
  onSurface: '#1a1b20',
  onSurfaceVariant: '#45464f',
  outline: '#767780',
  outlineVariant: '#c6c6d0',
  radius: '16px',
  radiusSmall: '12px',
} as const;

export type DesignTokenName = keyof typeof designTokens;
