import { useCallback, useEffect, useRef, useState } from 'react';

export type PresenceState = 'entering' | 'present' | 'exiting';

/**
 * Spring-driven exit timings, mirroring the `--m3-spring-*` tokens. The numbers
 * are generated by `scripts/motion-tokens.ts`; keep them in sync via
 * `pnpm tokens:motion`.
 *
 * Components must read the exit duration from here rather than hardcoding a
 * value, otherwise a component can unmount before its exit transition has
 * visually finished (or long after).
 */
export const SPRING_DURATION = {
  'spatial-fast': 225,
  spatial: 317,
  'spatial-slow': 487,
  'effects-fast': 150,
  effects: 233,
  'effects-slow': 329,
  'expressive-spatial-fast': 362,
  'expressive-spatial': 437,
  'expressive-spatial-slow': 600,
} as const;

export type SpringSpeed = keyof typeof SPRING_DURATION;

/**
 * Mount/enter/exit lifecycle for overlays. Elements stay mounted through the
 * exit transition so the closing animation can actually play.
 */
export function usePresence(open: boolean, exitDuration: number = SPRING_DURATION.effects) {
  const [mounted, setMounted] = useState(open);
  const [state, setState] = useState<PresenceState>(open ? 'present' : 'exiting');
  const duration =
    typeof window !== 'undefined' && window.matchMedia('(prefers-reduced-motion: reduce)').matches
      ? 1
      : exitDuration;

  useEffect(() => {
    let frame = 0;
    let timer: number | undefined;
    if (open) {
      setMounted(true);
      setState('entering');
      frame = window.requestAnimationFrame(() => setState('present'));
    } else if (mounted) {
      setState('exiting');
      timer = window.setTimeout(() => setMounted(false), duration);
    }
    return () => {
      if (frame) window.cancelAnimationFrame(frame);
      if (timer) window.clearTimeout(timer);
    };
  }, [duration, mounted, open]);

  return { mounted, state };
}

/** True when the user asked the OS to reduce motion. */
export function prefersReducedMotion(): boolean {
  return (
    typeof window !== 'undefined' &&
    typeof window.matchMedia === 'function' &&
    window.matchMedia('(prefers-reduced-motion: reduce)').matches
  );
}

/**
 * Tracks the active M3E window size class. The breakpoints match
 * `apps/web/src/styles/responsive.css`.
 */
export type WindowSizeClass = 'compact' | 'medium' | 'expanded' | 'large' | 'xlarge';

const SIZE_CLASSES: ReadonlyArray<{ min: number; value: WindowSizeClass }> = [
  { min: 1600, value: 'xlarge' },
  { min: 1200, value: 'large' },
  { min: 840, value: 'expanded' },
  { min: 600, value: 'medium' },
  { min: 0, value: 'compact' },
];

export function windowSizeClass(width: number): WindowSizeClass {
  return SIZE_CLASSES.find((entry) => width >= entry.min)?.value ?? 'compact';
}

export function useWindowSizeClass(): WindowSizeClass {
  const [sizeClass, setSizeClass] = useState<WindowSizeClass>(() =>
    typeof window === 'undefined' ? 'compact' : windowSizeClass(window.innerWidth),
  );

  useEffect(() => {
    if (typeof window === 'undefined') return;
    const update = () => setSizeClass(windowSizeClass(window.innerWidth));
    update();
    window.addEventListener('resize', update);
    return () => window.removeEventListener('resize', update);
  }, []);

  return sizeClass;
}

/** True for compact/medium — the tiers that use the touch-first shell. */
export function isCompactShell(sizeClass: WindowSizeClass): boolean {
  return sizeClass === 'compact' || sizeClass === 'medium';
}

/**
 * Menu/disclosure behaviour: outside click and Escape dismiss, with focus
 * restoration to the trigger.
 */
export function useDismissibleMenu(open: boolean, onClose: () => void) {
  const ref = useRef<HTMLDivElement | null>(null);
  useEffect(() => {
    if (!open) return;
    const onPointerDown = (event: MouseEvent) => {
      if (ref.current && !ref.current.contains(event.target as Node)) onClose();
    };
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        event.preventDefault();
        onClose();
      }
    };
    document.addEventListener('mousedown', onPointerDown);
    document.addEventListener('keydown', onKeyDown);
    return () => {
      document.removeEventListener('mousedown', onPointerDown);
      document.removeEventListener('keydown', onKeyDown);
    };
  }, [onClose, open]);
  return ref;
}

/**
 * Roving-tabindex navigation shared by segmented buttons, button groups and
 * navigation bars. Implements the WAI-ARIA radiogroup keyboard contract the
 * previous segmented control already honoured.
 */
export function useRovingFocus<T extends string>(
  values: readonly T[],
  current: T,
  onSelect: (value: T) => void,
  isDisabled: (value: T) => boolean = () => false,
) {
  const refs = useRef<Array<HTMLElement | null>>([]);

  const move = useCallback(
    (from: number, direction: 1 | -1) => {
      for (let offset = 1; offset <= values.length; offset += 1) {
        const index = (from + offset * direction + values.length) % values.length;
        const candidate = values[index]!;
        if (!isDisabled(candidate)) {
          refs.current[index]?.focus();
          onSelect(candidate);
          return;
        }
      }
    },
    [isDisabled, onSelect, values],
  );

  const onKeyDown = useCallback(
    (event: { key: string; preventDefault: () => void }, index: number) => {
      const lastEnabled = () => {
        for (let cursor = values.length - 1; cursor >= 0; cursor -= 1) {
          if (!isDisabled(values[cursor]!)) return cursor;
        }
        return -1;
      };
      if (event.key === 'ArrowRight' || event.key === 'ArrowDown') {
        event.preventDefault();
        move(index, 1);
      } else if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') {
        event.preventDefault();
        move(index, -1);
      } else if (event.key === 'Home') {
        event.preventDefault();
        const first = values.findIndex((value) => !isDisabled(value));
        if (first >= 0) {
          refs.current[first]?.focus();
          onSelect(values[first]!);
        }
      } else if (event.key === 'End') {
        event.preventDefault();
        const last = lastEnabled();
        if (last >= 0) {
          refs.current[last]?.focus();
          onSelect(values[last]!);
        }
      }
    },
    [isDisabled, move, onSelect, values],
  );

  const setRef = useCallback(
    (index: number) => (element: HTMLElement | null) => {
      refs.current[index] = element;
    },
    [],
  );

  return { setRef, onKeyDown, isSelected: (value: T) => value === current };
}

/**
 * Traps keyboard focus inside an overlay and restores it to the previously
 * focused element on close. Shared by dialogs, sheets and the drawer so the
 * three cannot drift apart.
 */
const focusTrapStack: HTMLElement[] = [];

export function useFocusTrap(
  ref: { readonly current: HTMLElement | null },
  active: boolean,
  onEscape?: () => void,
) {
  const escapeRef = useRef(onEscape);
  escapeRef.current = onEscape;

  useEffect(() => {
    const container = ref.current;
    if (!container || !active) return;
    const restoreTo = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    focusTrapStack.push(container);
    const focusable = () =>
      Array.from(
        container.querySelectorAll<HTMLElement>(
          'button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), a[href], [tabindex]:not([tabindex="-1"])',
        ),
      );
    const first =
      container.querySelector<HTMLElement>('[data-autofocus], [data-modal-autofocus]') ??
      focusable()[0];
    first?.focus();

    const onKeyDown = (event: KeyboardEvent) => {
      if (focusTrapStack.at(-1) !== container) return;
      if (event.key === 'Escape' && escapeRef.current) {
        event.preventDefault();
        escapeRef.current();
        return;
      }
      if (event.key !== 'Tab') return;
      if (!container.contains(document.activeElement)) return;
      const elements = focusable();
      if (elements.length === 0) return;
      const firstElement = elements[0]!;
      const lastElement = elements[elements.length - 1]!;
      if (event.shiftKey && document.activeElement === firstElement) {
        event.preventDefault();
        lastElement.focus();
      } else if (!event.shiftKey && document.activeElement === lastElement) {
        event.preventDefault();
        firstElement.focus();
      }
    };
    document.addEventListener('keydown', onKeyDown);
    return () => {
      document.removeEventListener('keydown', onKeyDown);
      const index = focusTrapStack.indexOf(container);
      if (index >= 0) focusTrapStack.splice(index, 1);
      if (restoreTo?.isConnected) restoreTo.focus({ preventScroll: true });
    };
  }, [active, ref]);
}

/**
 * Locks background scrolling while an overlay is open. Kept in one place so
 * dialogs, sheets and the navigation drawer cannot disagree about whether the
 * page behind them may scroll.
 */
const scrollLocks = new Map<string, number>();
let unlockedOverflow = '';

export function useScrollLock(active: boolean, className = 'modal-open') {
  useEffect(() => {
    if (!active || typeof document === 'undefined') return;
    if (scrollLocks.size === 0) {
      unlockedOverflow = document.body.style.overflow;
      document.body.style.overflow = 'hidden';
    }
    scrollLocks.set(className, (scrollLocks.get(className) ?? 0) + 1);
    document.documentElement.classList.add(className);
    // Do not put touch-action:none on body: it also disables scrolling inside
    // portalled dialogs on touch devices. The background scrollport is locked by CSS.
    return () => {
      const count = (scrollLocks.get(className) ?? 1) - 1;
      if (count > 0) scrollLocks.set(className, count);
      else {
        scrollLocks.delete(className);
        document.documentElement.classList.remove(className);
      }
      if (scrollLocks.size === 0) document.body.style.overflow = unlockedOverflow;
    };
  }, [active, className]);
}

/** Optional haptic confirmation on supported devices. */
export function haptic(pattern: number | number[] = 8): void {
  if (typeof navigator === 'undefined' || typeof navigator.vibrate !== 'function') return;
  if (prefersReducedMotion()) return;
  try {
    navigator.vibrate(pattern);
  } catch {
    // Vibration is a progressive enhancement; never let it break an interaction.
  }
}
